stages:
- name: push
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ctfbot:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: ghcr.io
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
branch:
  include:
  - master
notification: {}
