stages:
- name: push
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ctfbot:latest
      registry: index.docker.io
branch:
  include:
  - master
notification: {}
