kind: Service
apiVersion: v1
metadata:
  name: ctfbot-service
spec:
  selector:
    app: ctfbot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-ctfbot
  labels:
    app: ctfbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctfbot
  template:
    metadata:
      labels:
        app: ctfbot
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: ctfbot
        image: ctfbot:latest
