kind: Service
apiVersion: v1
metadata:
  name: discord-bot
  namespace: default
spec:
  selector:
    app: discord-bot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: discord-bot
  labels:
    app: discord-botr
    version: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
      version: develop
  template:
    metadata:
      labels:
        app: discord-bot
        version: develop
    spec:
      containers:
      - name: discord-bot
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
