apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctfbot
  labels:
    app: deployment-ctfbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-ctfbot
  template:
    metadata:
      labels:
        app: deployment-ctfbot
    spec:
      containers:
      - name: ctfbot
        image: ghcr.io/leppan02/ctfbot:latest
