apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctfbot
  labels:
    app: deployment-ctfbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-ctfbot
  template:
    metadata:
      labels:
        app: deployment-ctfbot
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: deployment-ctfbot
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        env:
        - name: APIKEY
          valueFrom:
            secretKeyRef:
              key: discord-key
              name: botapikey